name: Run Shell Commands
on: [push]

jobs:
  run-shell-command:
    rusn-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Security Gurus!! This is our first GitHub Actions Workflow file"